language: erlang
sudo: required
# Install cassandra
# Standard Travis cassandra is 2.0.9
# Docker runs on Trusty planform (the new one)
install:
    - docker run -d --net=host -e MAX_HEAP_SIZE=128M -e HEAP_NEWSIZE=64M --name=cassandra cassandra:${CASSANDRA_VERSION}
    - ./wait_for_cassandra.sh || docker logs cassandra
script:
    - ./rebar skip_deps=true eunit -v

services:
        - docker

otp_release:
    - R16B03
    - 17.5
    - 18.1

env:
    - CASSANDRA_VERSION=2.1
    - CASSANDRA_VERSION=3.1
    - CASSANDRA_VERSION=3.2
